default_platform(:ios)

platform :ios do

  private_lane :authenticate_api_key do
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_B64"],
      is_key_content_base64: true
    )
  end

  desc "ONE-TIME SETUP: Generate fresh certs and push to Git Vault"
  lane :generate_certs do
    authenticate_api_key
    match(
      type: "adhoc",
      readonly: false,
      force: true
    )
  end

  desc "BUILD & DISTRIBUTE: Fetch certs, compile app, and upload to Firebase"
  lane :firebase_beta do
    authenticate_api_key
    setup_ci

    # Fetch existing profile from match git repository
    match(
      type: "adhoc",
      readonly: true
    )

    # Compile the app using the match AdHoc profile
    gym(
      workspace: "ios/QliniQKiosk.xcworkspace", 
      scheme: "QliniQKiosk",                    
      clean: true,
      export_method: "ad-hoc",
      export_options: {
        method: "ad-hoc",
        provisioningProfiles: {
          "com.scyllatech.qliniqkiosk" => "match AdHoc com.scyllatech.qliniqkiosk"
        }
      },
      xcargs: "DEVELOPMENT_TEAM='3M66ZMAKG3' CODE_SIGN_STYLE='Manual' CODE_SIGN_IDENTITY='Apple Distribution' PROVISIONING_PROFILE_SPECIFIER='match AdHoc com.scyllatech.qliniqkiosk'"
    )

    # Upload to Firebase App Distribution
   firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID"],
      groups: "test-1",  # Automatically sends invite email to everyone in the 'testers' group
      release_notes: "Automated build from GitHub Actions"
    )
  end

end