name: Android CI Demo

on:
  workflow_dispatch:

jobs:
  android-ci:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      - name: Install Fastlane
        run: bundle install

      - name: Check Fastlane
        run: bundle exec fastlane --version

      # Start Upterm BEFORE Fastlane
      - name: Start Upterm
        uses: lhotari/action-upterm@v1

      - name: Run Fastlane
        run: bundle exec fastlane android test
