name: iOS Fastlane Test

on:
  workflow_dispatch:

jobs:
  ios-test:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      - name: Install Fastlane
        run: bundle install

      - name: Check Fastlane
        run: bundle exec fastlane --version

      - name: Start Upterm
        uses: lhotari/action-upterm@v1

      - name: Run Fastlane
        run: bundle exec fastlane ios test

